import type { Metadata } from "next";
import { Commissioner, Concert_One, Geist } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { NeonAuthUIProvider, UserButton } from "@neondatabase/auth/react";
import { authClient } from "@/lib/auth/client";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const commissioner = Commissioner({
  variable: "--font-commissioner",
  subsets: ["latin"],
});

const concert_one = Concert_One({
  variable: "--font-concert-one",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", commissioner.variable, concert_one.variable, "font-sans", geist.variable)}
      suppressHydrationWarning
    >
      <body className="bg-slate-200/50 ">
        <NeonAuthUIProvider authClient={authClient}>
          <main className="h-screen container mx-auto overflow-hidden text-black">

            <header className="flex justify-between items-center mx-auto p-4">
              <Link href="/" className="font-semibold text-xl"><span>Events Manager</span></Link>
              <UserButton size="icon" />
            </header>
            {children}

          </main>
        </NeonAuthUIProvider>
      </body>
    </html>
  );
}
